### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by hsooolee** [hsooolee/DragAndDrop#1]
tsconifg에서 es6 이전으로 설정하면 babel 없이도 이전 문법으로 변환해주나요?

**Comment by hsooolee** [comment]
알고 계신 거 처럼,
ts로 작성된 코드는 컴파일 시
tsconfig에 지정된 target으로 js로 변환을 해주는데요
(https://www.typescriptlang.org/docs/handbook/compiler-options.html)

현재 프로젝트도 babel이 구성되어 있지 않지만,
target을 다른 버전으로 변경하면, js로 변환이 됩니다!

그러나,
이 결과 물은 프로젝트 환경/상황에 따라
타켓 브라우저에서 지원하지 않는 문법등이 있을 수도 있을 거같은데요
이럴 때는 바벨을 통해 해당 문법들을 지원하는 형태로 변환 과정이 필요 할 거 같습니다.

정리하면,
ts는 타입 검사와 같은 타입스크립트 오류 검사와 같은 걸 수행해하는 역할에 초점이 맞춰져서 사용하고,
babel은 다양한 브라우저에서 지원을 위해서는 js를 transpile 하는 역할에 초점을 맞춰 사용하면 좋지 않을까라는 생각이듭니다.

다른 의견있으시면 답변 부탁드립니다 :) 

- https://babeljs.io/
- https://www.typescriptlang.org/ko/docs/handbook/babel-with-typescript.html

**Comment by parkjihwanjay** [comment]
결국 ts, babel의 역할에 초점을 맞춰 사용하면 되는군요!
친절한 답변 감사드립니다 :) 👍
